version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - automd
  - bumpp
  - changelogithub
  - crouchcd
  - defu
  - denoland
  - elysia
  - eslintcache
  - fumadocs
  - huggingface
  - importantimport
  - itty
  - masknet
  - modelcontextprotocol
  - moeru
  - PKCE
  - pkgroll
  - Pretrained
  - sonarjs
  - streamable
  - tolist
  - twoslash
  - valibot
  - vercel
  - webgpu
  - whatwg
  - Xenova
  - xsai
  - xsmcp
  - xsrpc
  - xsschema
ignoreWords: []
import: []
